### ISSUE TITLE
No fp16 support from fast-transformers (CausalDotProduct)

### ISSUE THREAD

**Issue by gulnazaki** [lucidrains/performer-pytorch#44]
There is the following `RuntimeError: expected scalar type Float but found Half` when using fp16 (for causal attention). 

That is because the fast-transformers' `CausalDotProduct` doesn't support fp16. Do you think there is any workaround, because using Float is bad news for memory usage and also disables DeepSpeed ZeRO optimizations?

**Comment by lucidrains** [comment]
Not at the moment unfortunately :( I noticed that as well

I may have to look into rewriting EPFLs code with Cutlass https://github.com/NVIDIA/cutlass

**Comment by gulnazaki** [comment]
I may be too naive, because i have never written cuda kernels, but wouldn't just changing float to half in the origina cuda code work?

**Comment by lucidrains** [comment]
im looking it up now https://stackoverflow.com/questions/32735292/can-anyone-provide-sample-code-demonstrating-the-use-of-16-bit-floating-point-in

**Comment by lucidrains** [comment]
@gulnazaki this may be painful lol

**Comment by lucidrains** [comment]
https://github.com/lucidrains/performer-pytorch/releases/tag/0.12.2 @gulnazaki do you want to give this a try?

**Comment by lucidrains** [comment]
hacky i know

**Comment by gulnazaki** [comment]
Haha nice and quick hack, I'll give it a try. 

If I have time I will do some reading on mixed precision, because it could really speed up the causal attention too.

Thanks

**Comment by lucidrains** [comment]
no problem, i'll start reading up on cuda_fp16.h and all it provides

**Comment by gulnazaki** [comment]
After a few iterations I got the following:

Traceback (most recent call last):
  File "train_performer.py", line 180, in <module>
    model_engine.backward(loss)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/engine.py", line 922, in backward
    self.optimizer.backward(loss)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/zero/stage1.py", line 732, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/fp16/loss_scaler.py", line 53, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 123, in backward
    y, dy = block.backward_pass(y, dy, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 93, in backward_pass
    torch.autograd.backward(fx2, dx1, retain_graph=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 123, in backward
    y, dy = block.backward_pass(y, dy, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 92, in backward_pass
    fx2 = self.f(x2, set_rng=True, **f_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 50, in forward
    return self.net(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 228, in forward
    return self.fn(self.norm(x), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 302, in forward
    out = self.fast_attention(q, k, v)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 192, in forward
    q = create_kernel(q, is_query = True)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 45, in softmax_kernel
    data_dash = torch.einsum('...id,...jd->...ij', (data_normalizer * data), projection)
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 344, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: Expected object of scalar type Half but got scalar type Float for argument #2 'mat2' in call to _th_bmm_out

**Comment by lucidrains** [comment]
https://github.com/lucidrains/performer-pytorch/releases/tag/0.12.3 I think this should fix it *fingers crossed*

**Comment by gulnazaki** [comment]
I think it fixes it too but when generating with fp16 there is the following error:

```
Traceback (most recent call last):
  File "train_performer.py", line 198, in <module>
    out = model.generate(inp.to(device), initial.to(device), seq_len=dataset.max_output_length, eos_token=2)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_enc_dec.py", line 69, in generate
    return self.dec.generate(seq_out_start, seq_len, context = encodings, **{**dec_kwargs, **kwargs})
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/autoregressive_wrapper.py", line 63, in generate
    sample = torch.multinomial(probs, 1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by lucidrains** [comment]
@gulnazaki almost there! https://github.com/lucidrains/performer-pytorch/releases/tag/0.12.4

**Comment by gulnazaki** [comment]
Oh, I see I did this one myself. Almost correct, I think you have to do the `kwargs.update(context_mask = context_mask)` outside the if, because if context_mask is provided it is popped and never updated. (it gave me a runtime error when I used a mask)

**Comment by gulnazaki** [comment]
Otherwise it seems fine, just to let you know it won't work with [amp/apex](https://github.com/NVIDIA/apex) because of the https://github.com/lucidrains/performer-pytorch/issues/44#issuecomment-741034223. 

But fp16 works fine.

**Comment by lucidrains** [comment]
ok fixed!

oh, why won't it work with amp?

**Comment by lucidrains** [comment]
@gulnazaki ok, i figured out what you were talking about, fixed in https://github.com/lucidrains/performer-pytorch/releases/tag/0.12.6

**Comment by lucidrains** [comment]
ugh! this is why i don't do custom CUDA code lol

**Comment by gulnazaki** [comment]
Hey, I should add that I observed a lot of NaN losses with fp16.

**Comment by lucidrains** [comment]
@gulnazaki oh no, is this with deepspeed?

**Comment by lucidrains** [comment]
@gulnazaki i'll do an amp run today

**Comment by lucidrains** [comment]
@gulnazaki also, I think this new experimental feature is worth trying https://github.com/pytorch/pytorch/issues/42368 , in the case that we can use it to get rid of the CUDA code

**Comment by gulnazaki** [comment]
Yep, I noticed it with deepspeed fp16 and amp (under deepspeed) opt_level O2 (O1 would give the https://github.com/lucidrains/performer-pytorch/issues/44#issuecomment-741034223)

**Comment by lucidrains** [comment]
@gulnazaki could you try O1 but with `amp_enabled = True` in your Performer constructor?

**Comment by lucidrains** [comment]
@gulnazaki i got AMP working with enwik8 (i'll check it in soon) and no NaNs. are you doing gradient clipping?

**Comment by gulnazaki** [comment]
Yep, I forgot adding `amp_enabled  = True`. I will try it after the current training finishes. I used clipping in the form `"max_grad_norm": 0.5` like you do in the enwik8 example.

**Comment by lucidrains** [comment]
@gulnazaki yea, i was looking for a way to auto-detect the AMP autocast context. I should probably just set it automatically without that flag

**Comment by lucidrains** [comment]
@gulnazaki just generated the samples from autoregressive enwik8 and it looks great! yea, i think amp should be fine, if deepspeed can use that

**Comment by gulnazaki** [comment]
I'll let you know about deepspeed and amp O1 in a few days too

**Comment by gulnazaki** [comment]
Error on the encoder's side. (I am testing the EncoderDecoder)

```
Traceback (most recent call last):
  File "train_performer.py", line 237, in <module>
    loss = model_engine(inp.to(device), out.to(device), enc_mask=inp_mask.to(device), dec_mask=out_mask.to(device), return_loss=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/engine.py", line 855, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_enc_dec.py", line 75, in forward
    encodings = self.enc(seq_in, return_encodings = True, **enc_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 389, in forward
    x = self.performer(x, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 357, in forward
    return self.net(x, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 155, in forward
    out =  _ReversibleFunction.apply(x, blocks, args)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 113, in forward
    x = block(x, **kwarg)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 65, in forward
    y1 = x1 + self.f(x2, record_rng=self.training, **f_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 40, in forward
    return self.net(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 231, in forward
    return self.fn(self.norm(x), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 305, in forward
    out = self.fast_attention(q, k, v)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 199, in forward
    out = attn_fn(q, k, v)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 120, in linear_attention
    context = torch.einsum('...nd,...ne->...de', k, v)
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 344, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: Expected object of scalar type Float but got scalar type Half for argument #2 'mat2' in call to _th_bmm_out
```

**Comment by lucidrains** [comment]
@gulnazaki that's been fixed in the latest patch!

**Comment by gulnazaki** [comment]
I had upgraded to 0.12.8 though

**Comment by lucidrains** [comment]
@gulnazaki oh doh, there was a bug with the redrawing projections feature and reversible networks

do you want to give the latest version a try? *fingers crossed*

**Comment by gulnazaki** [comment]
Yeah, I'll look into it shortly.

Do you think the redrawing projections bug would affect also a fp32 model with reversible layers that I have trained?

**Comment by lucidrains** [comment]
I think it may be a little worse, because the model may not have reconstructed the correct activations on the backward pass, but pretty rarely depending on the feature redraw interval

**Comment by lucidrains** [comment]
Just keep training from where you left off and it should recover!

**Comment by gulnazaki** [comment]
There is a mismatch in the state_dict keys but I guess loading with `strict=False` will suffice, right?

**Comment by lucidrains** [comment]
@gulnazaki ohh, i know why, but that state (the counter for how long until redrawing the next projection) isn't critical, yup, just override it!

**Comment by gulnazaki** [comment]
Ok, now there is an error in the softmax kernel. (DeepSpeed: amp enabled, opt_level O1) :stuck_out_tongue: 

```
Traceback (most recent call last):
  File "train_performer.py", line 325, in <module>
    loss = model_engine(inp.to(device), out.to(device), enc_mask=inp_mask.to(device), dec_mask=out_mask.to(device), return_loss=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/engine.py", line 855, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_enc_dec.py", line 75, in forward
    encodings = self.enc(seq_in, return_encodings = True, **enc_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 402, in forward
    x = self.performer(x, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 373, in forward
    return self.net(x, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 155, in forward
    out =  _ReversibleFunction.apply(x, blocks, args)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 113, in forward
    x = block(x, **kwarg)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 65, in forward
    y1 = x1 + self.f(x2, record_rng=self.training, **f_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 40, in forward
    return self.net(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 223, in forward
    return self.fn(self.norm(x), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 297, in forward
    out = self.fast_attention(q, k, v)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 187, in forward
    q = create_kernel(q, is_query = True)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 46, in softmax_kernel
    data_dash = torch.einsum('...id,...jd->...ij', (data_normalizer * data), projection)
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 344, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: Expected object of scalar type Half but got scalar type Float for argument #2 'mat2' in call to _th_bmm_out
```

**Comment by lucidrains** [comment]
@gulnazaki https://github.com/lucidrains/performer-pytorch/releases/tag/0.14.1 reversible nets man

**Comment by lucidrains** [comment]
@gulnazaki 🤞

**Comment by gulnazaki** [comment]
Sorry for that, but it's the same as in https://github.com/lucidrains/performer-pytorch/issues/44#issuecomment-742923063

```
Traceback (most recent call last):
  File "train_performer.py", line 325, in <module>
    loss = model_engine(inp.to(device), out.to(device), enc_mask=inp_mask.to(device), dec_mask=out_mask.to(device), return_loss=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deepspeed/runtime/engine.py", line 855, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_enc_dec.py", line 75, in forward
    encodings = self.enc(seq_in, return_encodings = True, **enc_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 404, in forward
    x = self.performer(x, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 375, in forward
    return self.net(x, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 155, in forward
    out =  _ReversibleFunction.apply(x, blocks, args)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 113, in forward
    x = block(x, **kwarg)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 65, in forward
    y1 = x1 + self.f(x2, record_rng=self.training, **f_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/reversible.py", line 40, in forward
    return self.net(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 225, in forward
    return self.fn(self.norm(x), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 299, in forward
    out = self.fast_attention(q, k, v)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 193, in forward
    out = attn_fn(q, k, v)
  File "/usr/local/lib/python3.6/dist-packages/performer_pytorch/performer_pytorch.py", line 122, in linear_attention
    context = torch.einsum('...nd,...ne->...de', k, v)
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 344, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: Expected object of scalar type Float but got scalar type Half for argument #2 'mat2' in call to _th_bmm_out
```

**Comment by lucidrains** [comment]
@gulnazaki perfect confluence of problems - reversibility, feature redraws, custom cuda code that only works with floats

so, I think I may have to put the mixed precision on hold, because I just found out that the current implementation of Performer encoder / decoder doesn't even pass a basic copy task https://github.com/lucidrains/performer-pytorch/blob/main/examples/toy_tasks/enc_dec_copy.py

In contrast, all my other frameworks can pass this test quite easily (routing transformers) https://github.com/lucidrains/routing-transformer/tree/master/examples/toy_tasks and (full-attention transformer) https://github.com/lucidrains/x-transformers/tree/main/examples/toy_tasks

Let me keep staring at the code and figure out what may be wrong (I was able to get the toy task working for another similar type of attention https://github.com/lucidrains/linear-attention-transformer) so it must be some bug.

I'll resume this issue next week, have a good weekend!

**Comment by gulnazaki** [comment]
Yeah, I see. 

I will continue training for a while and then try with Routing Transformer and compare it. So far, I am seeing a decrease in losses and that the model really learns the structure of the output gradually, but perhaps it is too slow.

I will also have a look, but I can't promise anything since this architecture introduces concepts I am not so familiar with.

Thank you and have a nice weekend too.

**Comment by lucidrains** [comment]
@gulnazaki good news! I got the copy task working! it now converges twice as fast as the non-FAVOR linear attention, so optimism is renewed!

**Comment by lucidrains** [comment]
@gulnazaki I'll keep trying to debug the mixed precision next week

**Comment by lucidrains** [comment]
@gulnazaki i squeeze in yet another potential fix (but no guarantees) feel free to try in the latest version

**Comment by gulnazaki** [comment]
That's very nice, I will check if there is an improvement in convergence for my task too. But for now I am trying to get around the `ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group` when loading the optimizer before the latest changes, state_dict of the model loads just fine though.

**Comment by lucidrains** [comment]
I'm not entirely sure, this may be a problem specific to the linear attention flavor, since it seems to work fine for attention needing QK interaction. I'll keep digging into it

Yup, AMP works for both enc/dec and them separately. I'll try to port over my toy task over to Deepspeed and see if I can repro the issue

Thanks for the timely testing!

**Comment by gulnazaki** [comment]
Don't mention it, thanks for your help and fast replies!

Btw, I now looked at the toy example. You know that DeepSpeed uses the amp by Nvidia/apex and not the torch cuda amp, right?

**Comment by lucidrains** [comment]
@gulnazaki Yea, I'm determined to fix this! I checked in an example using apex in the toy tasks directory under example. Could you see if that example works for you? And see if it fixes your deepspeed setup?

**Comment by lucidrains** [comment]
hopefully the codebase is both pytorch amp and nvidia apex compatible now

**Comment by gulnazaki** [comment]
Well, the good news is that there are no errors due to type mismatch.

But, I get NaN losses. At first I was very excited that all worked smoothly with DeepSpeed and AMP opt_level O1, but after 200-300 steps I got NaN losses. I tried all opt_levels with or without DeepSpeed (used the same code as the one in your toy example), but losses would be NaN after a while (and loss scale would drop a lot). Finally, I tried using torch.cuda.amp as in your code, but again NaN losses started at around 400 steps. Seems weird to me, but it is not an uncommon situation https://github.com/pytorch/pytorch/issues/40497.

**Comment by lucidrains** [comment]
@gulnazaki nice! let's open a new issue for that! i checked the code and all the epsilons are added before division, so the source of it must be something else

how high is your learning rate? do you have gradient clipping enabled?

**Comment by gulnazaki** [comment]
I use warm up lr, I guess it must be around 0.0006 when losses get NaN. I use gradient clipping 0.5 with DeepSpeed, I checked and they take ths into account https://nvidia.github.io/apex/advanced.html#gradient-clipping.

**Comment by gulnazaki** [comment]
Oh, let me try changing eps of Adam.

**Comment by lucidrains** [comment]
@gulnazaki I'm trying to think if the masking could be the culprit https://github.com/lucidrains/performer-pytorch/blob/main/performer_pytorch/performer_pytorch.py#L324 but think it should be fine

**Comment by gulnazaki** [comment]
Ooof, I changed Adam eps from 1e-8 to 1e-4 and everything is fine now (at 500 steps). I will continue training and let you know if anything bad happens. I should have thought of it earlier.

**Comment by lucidrains** [comment]
Oh wow! Nice, eager to hear how well Performer works for you!

**Comment by gulnazaki** [comment]
Unfortunately, after 1.5 epoch NaN losses started appearing, but disappeared after some steps. But it seems the model was corrupted. The losses were also higher during the whole training.

(Orange and Dark Blue is train and val loss for float training (with tied embeddings), Red and Light Blue is train and val loss with amp opt_level O1 (without tied embeddings))
![image](https://user-images.githubusercontent.com/38190410/102076998-44870e80-3e11-11eb-9003-cc571f82a3cb.png)

**Comment by lucidrains** [comment]
Aww ok, that's a bit disappointing

I wonder if somewhere precision is needed that the network isn't receiving

I'll think about it some more this week!

**Comment by lucidrains** [comment]
https://github.com/lucidrains/performer-pytorch/blob/0.14.9/performer_pytorch/performer_pytorch.py#L148 ok, i'm really out of ideas this time! lol

**Comment by lucidrains** [comment]
Actually that's not true, perhaps the projection also needs to be carried out with enough precision. Let me comb through the Jax code base a bit more for clues later today

**Comment by lucidrains** [comment]
@gulnazaki I think the precision may be important, because I see this in the code https://github.com/google-research/google-research/blob/master/performer/fast_attention/jax/fast_attention.py#L93 and https://github.com/google-research/google-research/blob/master/performer/fast_attention/jax/fast_attention.py#L404

**Comment by gulnazaki** [comment]
Yeah, my hopes were up too :disappointed: 

Is there any chance this could have something to do with it (because of the _ReversibleFunction)? https://pytorch.org/docs/stable/notes/amp_examples.html#autocast-and-custom-autograd-functions

**Comment by gulnazaki** [comment]
It's a little complicated because they use bfloat16 by default (sounds great really, and it would save us a lot of hassle), but as far as I know it is mostly supported in TPUs.

**Comment by lucidrains** [comment]
> Yeah, my hopes were up too 
> 
> Is there any chance this could have something to do with it (because of the _ReversibleFunction)? https://pytorch.org/docs/stable/notes/amp_examples.html#autocast-and-custom-autograd-functions

do you think you could potentially do a run without reversibilty so we can rule this in or out?

**Comment by gulnazaki** [comment]
I tried not using reversible layers (had to use 1/4 of batch size, thanks reversible layers) but nothing changed.

**Comment by gulnazaki** [comment]
Btw, memory required is 1/4 but speed is also 1/4, this is expected right? (in the reversible resnet paper they do mention 3L computational cost)

**Comment by lucidrains** [comment]
@gulnazaki yup! that sounds about right

**Comment by gulnazaki** [comment]
Btw, I noticed more stable training with the reversible layers.

Also, @norabelrose wrote an [implementation](https://github.com/norabelrose/transformers-plus-performers) of performer attention (based on your repo) most code [here](https://github.com/norabelrose/transformers-plus-performers/blob/clean/src/transformers/modeling_performer_attention.py). I will take a look later if I can find any difference that would explain the NaN losses. I can see she also uses a [way](https://github.com/norabelrose/transformers-plus-performers/blob/clean/src/transformers/modeling_performer_attention.py#L362) that seems efficient (I haven't tested it yet) that doesn't uses the custom EPFL cuda kernel.

If you have time you could check it out, otherwise I'll try to look at it sometime and so some comparison runs.

**Comment by lucidrains** [comment]
@gulnazaki yea! Nora actually emailed me and we tested her implementation

Unfortunately it is still 2x slower and 2x more memory than the CUDA version

**Comment by lucidrains** [comment]
@gulnazaki you can checkout this branch if you are interested in trying yourself https://github.com/lucidrains/performer-pytorch/commit/e8626dbe5cbaaa283cdc73f531548f22de4088c6

**Comment by gulnazaki** [comment]
Nice, good to know. But, yeah :unamused: it would be nice not having this dependency. You tested the latest implementation, right?

**Comment by lucidrains** [comment]
Affirmative!

**Comment by madkoppa** [comment]
So where are we with this? From reading this thread it looks like amp/apex runs but not perfectly. However, for me pytorch native AMP does not work at all.
 `AssertionError: half tensors can only be used if nvidia apex is available`
I'm not doing any deepspeed stuff, just fp16 training with a swapped out nn.MultiHeadAttention and SelfAttention. Am I using it wrong?

**Comment by norabelrose** [comment]
@madkoppa I just [submitted a PR](https://github.com/idiap/fast-transformers/pull/74) adding fp16 support to the CausalDotProduct CUDA kernel over in the fast-transformers repo. I haven't really been able to test it and I'm new to CUDA kernel programming, so there's probably at least one or two fixes that will need to be made, but I know that the maintainers of the fast-transformers repo have been meaning to add fp16 support to CausalDotProduct for a while so I'm optimistic that it will get merged.
